StartupEvents.registry('block', e => {
    e.create('double_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('triple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('quadruple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('quintuple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('sextuple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('septuple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('octuple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    e.create('nonuple_compressed_cobblestone').textureAll('kubejs:item/example_item').requiresTool(true).tagBlock("mineable/pickaxe").soundType('stone')
    })